######################################################################
# Automatically generated by qmake (3.0) Thu Jan 26 22:55:20 2017
######################################################################

TEMPLATE = app
TARGET = sinkobox-controller
INCLUDEPATH += .

QT += widgets core gui

# Input
SOURCES += main.cpp \
	mainwindow.cpp \
	maincontent.cpp \
	settingscontent.cpp \
	infocontent.cpp

HEADERS += mainwindow.h \
	maincontent.h \
	settingscontent.h \
	infocontent.h
